# Generated by Django 5.0.1 on 2024-04-05 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_post', '0001_initial'),
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='emp_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_posted_emp', to='user_profiles.employer'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='prof_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_posted_prof', to='user_profiles.professor'),
        ),
    ]
