# Generated by Django 4.2.9 on 2024-04-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
        ('job_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='applied_job_posts', to='user_profiles.student'),
        ),
    ]
