# Generated by Django 4.2.9 on 2024-04-05 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_post', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='post_title',
            new_name='job_title',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='post_desc',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='post_posted_date',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='post_status',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='prof_id',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='job_posts_by_company', to='user_profiles.company'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='favourite_user',
            field=models.ManyToManyField(related_name='fovourite_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_close_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_desc',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_location',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_major',
            field=models.ManyToManyField(related_name='job_posts_by_major', to='user_profiles.major'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_posted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_requirements',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('internship', 'Intern'), ('part time', 'Part Time'), ('full time', 'full Time')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='poster_emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_posted_emp', to='user_profiles.employer'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='poster_prof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_posted_prof', to='user_profiles.professor'),
        ),
    ]
