# Generated by Django 4.2.9 on 2024-04-05 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
        ('job_post', '0003_rename_post_title_jobpost_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='poster_emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_posted_by_emp', to='user_profiles.employer'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='poster_prof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_posted_by_prof', to='user_profiles.professor'),
        ),
    ]
