# Generated by Django 4.2.9 on 2024-04-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0005_remove_jobpost_job_desc_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_location_lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_location_long',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
