# Generated by Django 4.2.9 on 2024-04-11 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_post', '0005_alter_jobpost_favourite_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='favourite_user',
            field=models.ManyToManyField(blank=True, related_name='favourite_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('internship', 'Intern'), ('part time', 'Part Time'), ('full time', 'Full Time')], default='', max_length=10),
        ),
    ]
