# Generated by Django 4.2.9 on 2024-04-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0006_alter_jobpost_favourite_user_alter_jobpost_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_desc',
            field=models.FileField(blank=True, null=True, upload_to='static/job_post/files'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_requirements',
            field=models.FileField(blank=True, null=True, upload_to='static/job_post/files'),
        ),
    ]
