# Generated by Django 4.2.9 on 2024-04-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0006_jobpost_job_location_lat_jobpost_job_location_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_address',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
