# Generated by Django 4.2.9 on 2024-04-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0007_alter_jobpost_job_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='job_desc',
            new_name='job_desc_file',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='job_requirements',
            new_name='job_requirement_file',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_desc_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_requirement_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
