# Generated by Django 5.0.1 on 2024-04-11 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('job_post', '0008_rename_job_desc_jobpost_job_desc_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='job_posts_by_company', to='company.company'),
        ),
    ]
