# Generated by Django 4.2.9 on 2024-04-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0009_alter_jobpost_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='job_posted_date',
            new_name='job_post_date',
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('internship', 'Internship'), ('part time', 'Part Time'), ('full time', 'Full Time')], default='', max_length=10),
        ),
    ]
