version: '3.8'

services: 
  django:
    container_name: django
    build:
      context: ./job_opportunity
    command: python manage.py runserver 0.0.0.0:8000    
    volumes: 
      - ./job_opportunity:/usr/src/app
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1