# Generated by Django 4.2.9 on 2024-04-13 08:26

from django.db import migrations, models
import job_post.models
import job_post.storage


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0002_jobpost_applicants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_desc_file',
            field=models.FileField(blank=True, null=True, storage=job_post.storage.OverwriteStorage(), upload_to=job_post.models.PathRename('job_post/job_desc_file')),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_requirement_file',
            field=models.FileField(blank=True, null=True, storage=job_post.storage.OverwriteStorage(), upload_to=job_post.models.PathRename('job_post/job_requirement_file')),
        ),
    ]
