# Generated by Django 4.2.9 on 2024-04-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
        ('job_post', '0003_alter_jobpost_job_desc_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_major',
            field=models.ManyToManyField(blank=True, related_name='job_posts_by_major', to='user_profiles.major'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
