# Generated by Django 4.2.9 on 2024-04-15 15:14

from django.db import migrations, models
import job_post.models
import job_post.storage


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0004_alter_jobpost_job_major_alter_jobpost_job_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='job_desc_file',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='job_requirement_file',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_info_file',
            field=models.FileField(blank=True, null=True, storage=job_post.storage.OverwriteStorage(), upload_to=job_post.models.PathRename('job_post/job_info_file')),
        ),
    ]
