# Generated by Django 4.2.9 on 2024-04-17 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0007_jobpost_job_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='job_address',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='job_location_lat',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='job_location_long',
        ),
    ]
