# Generated by Django 5.0.2 on 2024-04-19 06:06

import user_profiles.models
import user_profiles.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profiles", "0005_remove_portfolio_student_portfolio_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_resume",
            field=models.FileField(
                blank=True,
                null=True,
                storage=user_profiles.storage.OverwriteStorage(),
                upload_to=user_profiles.models.PathRename("user_profiles/Files"),
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=user_profiles.storage.OverwriteStorage(),
                upload_to=user_profiles.models.PathRename("user_profiles/Images"),
            ),
        ),
    ]
