# Generated by Django 5.0.2 on 2024-04-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_company_comp_address_company_comp_contact_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="comp_lat",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="comp_long",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
