# Generated by Django 5.0.1 on 2024-04-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_comp_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='comp_logo',
            field=models.ImageField(default='ompany/Images/default.jpg', null=True, upload_to='company/Images'),
        ),
    ]
