# Generated by Django 5.0.2 on 2024-04-19 06:06

import company.models
import company.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0004_alter_company_comp_lat_alter_company_comp_long"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="comp_logo",
            field=models.ImageField(
                default="company/Images/default.jpg",
                null=True,
                storage=company.storage.OverwriteStorage(),
                upload_to=company.models.PathRename("company/Images"),
            ),
        ),
    ]
