# Generated by Django 4.2.9 on 2024-04-19 12:52

import company.models
import company.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_comp_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='comp_logo',
            field=models.ImageField(default='company/Images/default.png', null=True, storage=company.storage.OverwriteStorage(), upload_to=company.models.PathRename('company/Images')),
        ),
    ]
