# Generated by Django 5.0.1 on 2024-04-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_alter_employer_emp_position_alter_user_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_portfolio',
            field=models.FileField(blank=True, null=True, upload_to='user_profiles/Portfolio'),
        ),
    ]
