# Generated by Django 5.0.1 on 2024-04-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_student_student_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_portfolio',
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_portfolio', models.FileField(blank=True, null=True, upload_to='user_profiles/Portfolio')),
                ('student', models.ManyToManyField(to='user_profiles.student')),
            ],
        ),
    ]
