# Generated by Django 5.0.1 on 2024-04-05 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='comp_logo',
            field=models.ImageField(default='static/user_profiles/Images/default.jpg', null=True, upload_to='static/user_profiles/Images'),
        ),
        migrations.AddField(
            model_name='professor',
            name='major_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prof_major_id', to='user_profiles.major'),
        ),
        migrations.AddField(
            model_name='student',
            name='major_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_major_id', to='user_profiles.major'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='comp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comp_id', to='user_profiles.company'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='prof_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approve_prof_id', to='user_profiles.professor'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emp_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='professor',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prof_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_resume',
            field=models.FileField(null=True, upload_to='static/user_profiles/Files'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
