# Generated by Django 5.0.1 on 2024-04-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_company_comp_logo_professor_major_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(null=True, upload_to='static/user_profiles/Images'),
        ),
    ]
