# Generated by Django 5.0.1 on 2024-04-09 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_user_user_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='comp_id',
            new_name='comp',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='prof_id',
            new_name='prof',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='major_id',
            new_name='major',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='major_id',
            new_name='major',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='user_id',
            new_name='user',
        ),
    ]
