# Generated by Django 4.2.9 on 2024-04-11 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0004_company_following_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='following_user',
        ),
        migrations.AddField(
            model_name='company',
            name='following_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='followed_company', to=settings.AUTH_USER_MODEL),
        ),
    ]
