# Generated by Django 5.0.1 on 2024-04-11 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('job_post', '0009_alter_jobpost_company'),
        ('user_profiles', '0006_alter_company_following_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='comp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comp_id', to='company.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='followed_company',
            field=models.ManyToManyField(blank=True, related_name='following_user', to='company.company'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
