# Generated by Django 5.0.1 on 2024-04-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0007_alter_employer_comp_id_user_followed_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='comp_id',
            new_name='comp',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='prof_id',
            new_name='prof',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='major_id',
            new_name='major',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='major_id',
            new_name='major',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_resume',
            field=models.FileField(blank=True, null=True, upload_to='media/user_profiles/Files'),
        ),
    ]
