# Generated by Django 5.0.1 on 2024-04-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0008_rename_comp_id_employer_comp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_resume',
            field=models.FileField(blank=True, null=True, upload_to='user_profiles/Files'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_profiles/Images'),
        ),
    ]
